import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./../globals.css";
import Sidebar from "../Components/admin/Sidebar";
import Navbar from "../Components/admin/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex">
        <div className="basis-1/4">
            <Sidebar />
        </div>
        <div className="basis-3/4 bg-blue-200/60">
          <Navbar />
          {children}
        </div>
    </div>
  );
}
